# -*- coding: utf-8 -*-
"""linearregression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13JTEkNqjoeESvxb3Ug7s3l_xHYlsGBBj
"""

import numpy as numpy

import numpy as np

#creating linear regression model
class Linear_Regression:
  def __init__(self,learning_rate,no_of_iterations):
    self.learning_rate = learning_rate
    self.no_of_iterations = no_of_iterations

  def fit(self,X,Y):
    self.m,self.n,=X.shape #no of rows and columns
    #iniciating weight and bias
    self.w = np.zeros(self.n)
    self.b = 0
    self.X = X
    self.Y = Y
    #implementing gradient decent
    for i in range(self.no_of_iterations):
      self.update_weight()



  def update_weight(self, ):
    Y_pred = self.predict(self.X)
    #calculate gradient
    dw = - (2 * (self.X.T).dot(self.Y - Y_pred)) / self.m
    db = - 2 * np.sum(self.Y - Y_pred) / self.m
    #updating the weights
    self.w = self.w - self.learning_rate * dw
    self.b = self.b - self.learning_rate * db



  def predict(self,X):
    return X.dot(self.w) + self.b

import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

#data preprocessing
salary_data = pd.read_csv('/content/salary_data.csv')

#printing the first 5 columns of the data frame
salary_data.head()

salary_data.tail()

salary_data.shape





#checking or mising values
salary_data.isnull().sum()

X = salary_data.iloc[:,:-1].values
Y = salary_data.iloc[:,1].values

print(X)

print(Y)

#splitting the dataset into training and text data
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=1/3,random_state = 2)

model = Linear_Regression(learning_rate=0.02,no_of_iterations=1000)

model.fit(X_train,Y_train)



print('weight = ', model.w[0])
print('bias = ', model.b)

#predicting the salary value for this data
test_data_prediction = model.predict(X_test)

print(test_data_prediction)

#visualizing predicted values and actual values
plt.scatter(X_test,Y_test, color ='red')
plt.plot(X_test,test_data_prediction, color = 'blue')
plt.xlabel('work experience')
plt.ylabel('salary')
plt.title('salary vs expericene')
plt.show()