# -*- coding: utf-8 -*-
"""LOGISTIC REGRESSION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tQbcWXaKIe72ixvD8NYk_D36BEpyRxpH
"""

import  numpy as np

"""logistic regression

"""

class Logistic_Regression():
  #declaring learning rate and number of iterations(hyperparameters)
  def __init__(self,learning_rate,no_of_iterations):
    self.learning_rate = learning_rate
    self.no_of_iterations = no_of_iterations

  #fit function to train the model
  def fit(self,x,y):
    #no of data points in the data set(---no of rows) -->m
    #no of inpot features in the dataset(--- no of column)-->n
    self.m,self.n = x.shape
    #initiating weight and bias value
    self.w = np.zeros(self.n)
    self.b = 0
    self.x = x
    self.y = y

    #implementing gradient decent for optimization
    for i in range(self.no_of_iterations):
      self.update_weights()


  def update_weights(self):
    #y_cap formula
    y_cap = 1/(1+np.exp(-(self.x.dot(self.w)+self.b)))
    #derivatives
    dw = (1/self.m)*np.dot(self.x.T,(y_cap-self.y))
    db = (1/self.m)*np.sum(y_cap-self.y)
    #updating the weights
    self.w = self.w - self.learning_rate*dw
    self.b = self.b - self.learning_rate*db

   #writing the sigmoid equation and decision boundary
  def predict(self,x):
    y_pred = 1/(1+np.exp(-(self.x.dot(self.w)+self.b)))
    y_pred = np.where(y_pred>0.5,1,0)
    return y_pred

model = Logistic_Regression(learning_rate = 0.01,no_of_iterations = 1000)

model.m